version: '3.7'

services:
    app:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        environment: 
            - DJANGO_SECRET_KEY=secret
            - DEBUG=0
    
    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "80:80"
        depends_on:
            - app

volumes:
    static_data:
